# Build stage: compile React client
FROM node:20.19-alpine AS client-build

WORKDIR /app/client
COPY client/package.json ./
RUN npm install
COPY client/ ./
RUN npm run build

# Note: sitemap.xml is pre-generated by rebuild.sh before Docker build
# This ensures it's fresh and includes all current ferries from data/ferries.json


# Runtime stage: Express server + built client
FROM node:20.19-alpine AS server

# Set Finland timezone so node-cron fires at the right local time
ENV TZ=Europe/Helsinki
ENV NODE_ENV=production
ENV DATA_DIR=/data

RUN apk add --no-cache tzdata

WORKDIR /app/server
COPY server/package.json ./
RUN npm install --omit=dev

COPY server/ ./

# Copy compiled React app so Express can serve it as static files
COPY --from=client-build /app/client/dist /app/client/dist

EXPOSE 3000

VOLUME ["/data"]

# Run as non-root user
RUN addgroup -S ferry && adduser -S -G ferry ferry
USER ferry

HEALTHCHECK --interval=30s --timeout=5s --start-period=15s --retries=3 \
  CMD wget -qO- http://localhost:3000/api/health || exit 1

CMD ["node", "src/index.js"]
